config/routes.rb
Overylayd::Application.routes.draw do
  resources :users

  resources :overlays

  resources :annotations

  resources :patterns

  root :to => 'overlays#index'
  

end

app/models/overlay.rb
#require 'imgkit'

class Overlay < ActiveRecord::Base
  has_many :annotations
  #after_create :create_picture
  attr_accessible :title, :name, :root_domain, :views, :subdomain, :picture, :site_name
  
  def link
    return "http://" + root_domain + ".overlayd.org"
  end
  
  def picture 
    return "assets/"+subdomain+".jpg"
  end
  def create_picture
    # kit = IMGKit.new(html, :quality => 50)
    kit = IMGKit.new("http://" + root_domain)
    f = File.new(Rails.root.join("app", "assets", "images", subdomain + ".jpg"), 'wb')
    img = kit.to_img(:jpg)
    f.write(img)
    f.close
    self.picture = "assets/"+subdomain+".jpg"
    self.save!
    return picture
  end
end

app/controllers/overlays_controller.rb
class OverlaysController < ApplicationController
  # GET /overlays
  # GET /overlays.json
  def index
    @overlay = Overlay.new
    @overlays = Overlay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overlays }
    end
  end

  # GET /overlays/1
  # GET /overlays/1.json
  def show
    @overlay = Overlay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @overlay }
    end
  end

  # GET /overlays/new
  # GET /overlays/new.json
  def new
    @overlay = Overlay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @overlay }
    end
  end

  # GET /overlays/1/edit
  def edit
    @overlay = Overlay.find(params[:id])
  end

  # POST /overlays
  # POST /overlays.json
  def create
    @overlay = Overlay.new(params[:overlay])
    @last = @overlay.root_domain[/(?:http:\/\/)?([^\/]+)(\/.+)?/, 2]
    @overlay.root_domain = @overlay.root_domain[/(?:http:\/\/)?([^\/]+)(\/.+)?/, 1]
    @overlay.subdomain ||= @overlay.root_domain[/(?:http:\/\/)?([a-zA-Z0-9\-]+)/, 1].downcase
    @overlay.title ||= @overlay.root_domain
    @overlay.site_name ||= @overlay.root_domain
    @overlay.picture = "assets/"+@overlay.subdomain+".jpg"

    respond_to do |format|
      if @overlay.save
        format.html { redirect_to "http://"+@overlay.root_domain[/(?:http:\/\/)?(.+)/, 1]+".overlayd.org"+@last, notice: 'Overlay was successfully created.' }
        format.json { render json: @overlay, status: :created, location: @overlay }
      else
        format.html { render action: "new" }
        format.json { render json: @overlay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /overlays/1
  # PUT /overlays/1.json
  def update
    @overlay = Overlay.find(params[:id])

    respond_to do |format|
      if @overlay.update_attributes(params[:overlay])
        format.html { redirect_to @overlay, notice: 'Overlay was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @overlay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overlays/1
  # DELETE /overlays/1.json
  def destroy
    @overlay = Overlay.find(params[:id])
    @overlay.destroy

    respond_to do |format|
      format.html { redirect_to overlays_url }
      format.json { head :ok }
    end
  end
end

app/helpers/overlays_helper.rb
module OverlaysHelper
end

app/views/overlays/_form.html.erb
<%= form_for(@overlay) do |f| %>
  <% if @overlay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overlay.errors.count, "error") %> prohibited this overlay from being saved:</h2>

      <ul>
      <% @overlay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :root_domain %><br />
    <%= f.text_field :root_domain %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :views %><br />
    <%= f.number_field :views %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br />
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/overlays/edit.html.erb
<h1>Editing overlay</h1>

<%= render 'form' %>

<%= link_to 'Show', @overlay %> |
<%= link_to 'Back', overlays_path %>

app/views/overlays/index.html.erb
  <div class="container2">
 <!-- Main hero unit for a primary marketing message or call to action -->

     <div class="hero-unit">
       <!--h1>Overlay.d</h1-->
       <img src="/assets/mainlogo.png" width="450"  />
       <p>
       	<span >
       	  <%= form_for(@overlay) do |f| %>
       		  <div class="hero-subunit"> <!-- was form -->
       		      <%= f.text_field :root_domain, :class => "input-xlarge" %>
       		    <a class="btn primary large" onclick="$('form').submit()">create overlay &raquo;</a>
       		  </div> <!-- was form -->
       		<% end %>
       	</span>
       </p>

     </div>
   </div>
 
 
 <div class="container">
    <!-- Example row of columns -->
    <% @num = 0 %>
    <% @overlays.each do |overlay| %>
    <% if @num %3 == 0 %>
        <% if @num != 0 %>
          </div> <!-- end row -->
        <% end %>
        <div class="row">
    <% end %>
    
     <div class="span5">
        <div class="boxgrid caption">  
        	<a href="<%= overlay.link %>"><img style="max-width: 600px; max-height: auto;" src="<%= overlay.picture %>"/></a>
        	<div class="cover boxcaption">  
            	<h3><%= overlay.root_domain %></h3>  
            	<p>
                <%= overlay.root_domain %>
                <%= link_to 'Show', overlay %>
                <%= link_to 'Edit', edit_overlay_path(overlay) %>
                <%= link_to 'Destroy', overlay, confirm: 'Are you sure?', method: :delete %>     
            </p>  
        	</div> <!-- end cover boxcaption -->
    	</div> <!-- end boxgrid caption -->

     </div> <!-- end span 5 -->
     <% @num += 1 %>
    <% end %>
    <% if @num %3 != 0 %>
      </div> <!-- end row -->
    <% end %>
   

<br />
  
</div>

app/views/overlays/new.html.erb
<h1>New overlay</h1>

<%= render 'form' %>

<%= link_to 'Back', overlays_path %>

app/views/overlays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @overlay.title %>
</p>

<p>
  <b>Site name:</b>
  <%= @overlay.site_name %>
</p>

<p>
  <b>Root domain:</b>
  <%= @overlay.root_domain %>
</p>

<p>
  <b>User:</b>
  <%= @overlay.user_id %>
</p>

<p>
  <b>Views:</b>
  <%= @overlay.views %>
</p>

<p>
  <b>Subdomain:</b>
  <%= @overlay.subdomain %>
</p>


<%= link_to 'Edit', edit_overlay_path(@overlay) %> |
<%= link_to 'Back', overlays_path %>