config/routes.rb
Overylayd::Application.routes.draw do
  resources :users

  resources :overlays

  resources :annotations

  resources :patterns

  root :to => 'overlays#index'
  

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  has_one :annotation
  attr_accessible :title, :description, :link
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patterns }
    end
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
    @pattern = Pattern.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pattern }
    end
  end

  # GET /patterns/new
  # GET /patterns/new.json
  def new
    @pattern = Pattern.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pattern }
    end
  end

  # GET /patterns/1/edit
  def edit
    @pattern = Pattern.find(params[:id])
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(params[:pattern])

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render json: @pattern, status: :created, location: @pattern }
      else
        format.html { render action: "new" }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patterns/1
  # PUT /patterns/1.json
  def update
    @pattern = Pattern.find(params[:id])

    respond_to do |format|
      if @pattern.update_attributes(params[:pattern])
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern = Pattern.find(params[:id])
    @pattern.destroy

    respond_to do |format|
      format.html { redirect_to patterns_url }
      format.json { head :ok }
    end
  end
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<h1>Listing patterns</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patterns.each do |pattern| %>
  <tr>
    <td><%= pattern.title %></td>
    <td><%= pattern.description %></td>
    <td><%= pattern.link %></td>
    <td><%= link_to 'Show', pattern %></td>
    <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
    <td><%= link_to 'Destroy', pattern, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pattern', new_pattern_path %>

app/views/patterns/new.html.erb
<h1>New pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @pattern.title %>
</p>

<p>
  <b>Description:</b>
  <%= @pattern.description %>
</p>

<p>
  <b>Link:</b>
  <%= @pattern.link %>
</p>


<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>