config/routes.rb
Overylayd::Application.routes.draw do
  resources :users

  resources :overlays

  resources :annotations

  resources :patterns

  root :to => 'overlays#index'
  

end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  has_one :overlay
  has_many :patterns
  attr_accessible :x, :y, :width, :height, :text, :title, :link, :path, :sub_domain, :selector
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @annotations }
    end
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show
    @annotation = Annotation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @annotation }
    end
  end

  # GET /annotations/new
  # GET /annotations/new.json
  def new
    @annotation = Annotation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @annotation }
    end
  end

  # GET /annotations/1/edit
  def edit
    @annotation = Annotation.find(params[:id])
  end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.new(params[:annotation])

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to @annotation, notice: 'Annotation was successfully created.' }
        format.json { render json: @annotation, status: :created, location: @annotation }
      else
        format.html { render action: "new" }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /annotations/1
  # PUT /annotations/1.json
  def update
    @annotation = Annotation.find(params[:id])

    respond_to do |format|
      if @annotation.update_attributes(params[:annotation])
        format.html { redirect_to @annotation, notice: 'Annotation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1
  # DELETE /annotations/1.json
  def destroy
    @annotation = Annotation.find(params[:id])
    @annotation.destroy

    respond_to do |format|
      format.html { redirect_to annotations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/views/annotations/_form.html.erb
<%= form_for(@annotation) do |f| %>
  <% if @annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% @annotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.number_field :text %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :pattern_id %><br />
    <%= f.number_field :pattern_id %>
  </div>
  <div class="field">
    <%= f.label :overlay_id %><br />
    <%= f.number_field :overlay_id %>
  </div>
  <div class="field">
    <%= f.label :page_path %><br />
    <%= f.text_field :page_path %>
  </div>
  <div class="field">
    <%= f.label :page_sub_domain %><br />
    <%= f.text_field :page_sub_domain %>
  </div>
  <div class="field">
    <%= f.label :selector %><br />
    <%= f.text_field :selector %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<h1>Listing annotations</h1>

<table>
  <tr>
    <th>X</th>
    <th>Y</th>
    <th>Width</th>
    <th>Height</th>
    <th>Text</th>
    <th>Title</th>
    <th>Link</th>
    <th>Pattern</th>
    <th>Overlay</th>
    <th>Page path</th>
    <th>Page sub domain</th>
    <th>Selector</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @annotations.each do |annotation| %>
  <tr>
    <td><%= annotation.x %></td>
    <td><%= annotation.y %></td>
    <td><%= annotation.width %></td>
    <td><%= annotation.height %></td>
    <td><%= annotation.text %></td>
    <td><%= annotation.title %></td>
    <td><%= annotation.link %></td>
    <td><%= annotation.pattern_id %></td>
    <td><%= annotation.overlay_id %></td>
    <td><%= annotation.page_path %></td>
    <td><%= annotation.page_sub_domain %></td>
    <td><%= annotation.selector %></td>
    <td><%= link_to 'Show', annotation %></td>
    <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
    <td><%= link_to 'Destroy', annotation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New annotation</h1>

<%= render 'form' %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>X:</b>
  <%= @annotation.x %>
</p>

<p>
  <b>Y:</b>
  <%= @annotation.y %>
</p>

<p>
  <b>Width:</b>
  <%= @annotation.width %>
</p>

<p>
  <b>Height:</b>
  <%= @annotation.height %>
</p>

<p>
  <b>Text:</b>
  <%= @annotation.text %>
</p>

<p>
  <b>Title:</b>
  <%= @annotation.title %>
</p>

<p>
  <b>Link:</b>
  <%= @annotation.link %>
</p>

<p>
  <b>Pattern:</b>
  <%= @annotation.pattern_id %>
</p>

<p>
  <b>Overlay:</b>
  <%= @annotation.overlay_id %>
</p>

<p>
  <b>Page path:</b>
  <%= @annotation.page_path %>
</p>

<p>
  <b>Page sub domain:</b>
  <%= @annotation.page_sub_domain %>
</p>

<p>
  <b>Selector:</b>
  <%= @annotation.selector %>
</p>


<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>